Algoritmo "semnome"
//  
//  
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/02/2023
Var
// Seção de Declarações das variáveis
n1:inteiro n2:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("escreva um numero")
 leia (N1)
     se(n1>0)entao
     escreva("daleee")
     senao(n1<0)entao
     escreva("uiii")
           fimse
Fimalgoritmo